trigger:
  branches:
    include:
      - main

  paths:
    include:
      - terraform-infra/**

pool:
  vmImage: ubuntu-latest

variables:
  AWS_REGION: ca-central-1

steps:


#install terraform
- script: |
    wget -q https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip

    unzip -o terraform_1.9.8_linux_amd64.zip

    sudo mv -f terraform /usr/local/bin/

    terraform version
  displayName: Install Terraform

# Verify AWS OIDC Authentication
- task: AWSCLI@1
  displayName: Verify AWS Identity
  inputs:
    awsCredentials: aws-odic-sc
    regionName: $(AWS_REGION)
    awsCommand: sts
    awsSubCommand: get-caller-identity

# Terraform Init
- script: |
    terraform init
  workingDirectory: terraform-infra
  displayName: Terraform Init

# Terraform Format Check
- script: |
    terraform fmt -check -recursive
  workingDirectory: terraform-infra
  displayName: Terraform Format Check

# Terraform Validate
- script: |
    terraform validate
  workingDirectory: terraform-infra
  displayName: Terraform Validate

# Terraform Plan
- task: AWSShellScript@1
  displayName: Terraform Plan
  inputs:
    awsCredentials: aws-odic-sc
    regionName: $(AWS_REGION)
    scriptType: inline
    inlineScript: |
      cd terraform-infra

      terraform plan \
        -out=tfplan \
        -input=false
  env:
    AWS_REGION: $(AWS_REGION)

# Terraform Apply
- task: AWSShellScript@1
  displayName: Terraform Apply
  inputs:
    awsCredentials: aws-odic-sc
    regionName: $(AWS_REGION)
    scriptType: inline
    inlineScript: |
      cd terraform-infra

      terraform apply \
        -auto-approve \
        -input=false \
        tfplan
  env:
    AWS_REGION: $(AWS_REGION)
 